modify make_clip_df to handle a single filepath string nicely
kitzeslab/opensoundscape pull request #463
Opened 2022-03-21 14:39 UTC by louisfh

This closes #456. I'm not sure if it is necessary. It may be better to warn the user they passed a string, instead of a list. Or it may be better to not address this issue at all.

2022-03-21 19:22 UTC, sammlapp requested changes
Let's give a helpful error instead. Broadly, I don't want to go down the path of trying to guess what users may have meant to be doing - if the provided arguments to a function don't fit the arguments listed in the docstring it should fail (ideally, with a helpful error message).

2022-03-22 18:29 UTC, louisfh commented
We should make this change for every function that accepts a list of files. I will check which functions do this.

2022-03-24 16:59 UTC, sammlapp approved these changes

2022-03-24 16:59 UTC, sammlapp commented
I think this is the right behavior, we can discuss more in the future if necessary

2022-03-24 17:00 UTC, merged